name: Deploy API


on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Chekcout main branch
      uses: actions/checkout@master

    - name: chalice deploy
      uses: 5tigerjelly/chalice-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
