name: Deploy API


on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ssh-key: {{ secrets.SSH_KEY }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt --user


    - name: chalice deploy
      run: |
        cd src/movie_api
        chalice deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Commit deployment file changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git commit -am "Update deployment json file"
        git push
