name: Deploy API


on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_KEY }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt --user

    - name: chalice deploy
      run: |
        cd src/movie_api
        chalice deploy
        aws lambda update-function-configuration \
          --function-name movie_api-dev \
          --environment "Variables={CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}}"
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    - name: Commit changes to repo
      uses: stefanzweifel/git-auto-commit-action@v5
